---

- name: Create Knative Operator Group
  delegate_to: localhost
  k8s:
    state: present
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('file', 'operatorgroup.yaml') }}"

