---

- name: Knative | Create Operator Group
  delegate_to: localhost
  k8s:
    state: present
    namespace: 'openshift-operators'
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/setup/operatorgroup.yaml') }}"

- name: Knative | Create Operator Subscription
  delegate_to: localhost
  k8s:
    state: present
    namespace: 'openshift-operators'
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/setup/sub.yaml') }}"

- name: Knative | Create knative-serving namespace
  delegate_to: localhost
  k8s:
    name: 'knative-serving'
    api_version: v1
    kind: Namespace
    state: present
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'

- name: Knative | Deploy Operator
  delegate_to: localhost
  k8s:
    state: present
    namespace: 'knative-serving'
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/setup/knative-serving.yaml') }}"
