---

- name: Kafka | Add Route
  delegate_to: localhost
  k8s:
    state: present
    namespace: kafka
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/bridge/route.yaml') }}"

- name: Kafka | Add Bridge
  delegate_to: localhost
  k8s:
    state: present
    namespace: kafka
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/bridge/kafka-bridge.yaml') }}"
