---

- name: TensorFlow | serving
  delegate_to: localhost
  k8s:
    state: present
    wait: true
    namespace: kafka
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/setup/tensorflowServing.yaml') }}"

