---

- name: Ceph | create iot-user
  delegate_to: localhost
  k8s_info:
    api_version: v1
    kind: secrets
    name: 'rook-ceph-object-user-my-store-{{ ceph_username }}'
    namespace: 'rook-ceph'
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
  register: ceph_secret
