---

- name: Ceph | create iot-user
  delegate_to: localhost
  k8s:
    state: present
    namespace: 'rook-ceph'
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/iot-dev-user.yaml') }}"

- name: Ceph | create custom user
  delegate_to: localhost
  k8s:
    state: present
    namespace: 'rook-ceph'
    wait: true
    kubeconfig: "{{ kubeconfig }}"
    validate_certs: '{{ kube_ssl_enabled }}'
    definition: "{{ lookup('template', 'templates/object-user.yaml') }}"
