apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gstreamer-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gstreamer
    spec:
      containers:
      - name: gstreamer
        image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display@sha256:37ace92b63fc516ad4c8331b6b3b2d84e4ab2d8ba898e387c0b6f68f0e3081c4
        ports:
        - containerPort: 8080

